name: format

on:
  push:
  pull_request:

jobs:
  csharpier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - run: dotnet tool restore

      - run: dotnet csharpier check .
